apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
  namespace: monitoring
  
spec:
  selector: 
    app: prometheus-server
  type: NodePort  
  ports:
    - port: {{.Values.promport}}
      targetPort: {{.Values.promport}}
      nodePort: 30000


