apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  
spec:
  selector: 
    app: prometheus-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: {{.Values.promport}}
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata: 
  namespace: monitoring
  name: goapp
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '2112'
spec:
  type: NodePort
  selector:
    app: golang
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: {{.Values.goport}}
      nodePort: 30001

