apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name:  {{.Release.Name}}
  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
        - name: gogo
          image: effy77/calipsa_task
          ports: 
            - containerPort: {{.Values.goport}}
  selector:
    matchLabels:
      app: golang

