apiVersion: v1
kind: Service
metadata: 
  namespace: monitoring
  name: {{.Release.Name}}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '{{.Values.goport}}'
spec:
  type: NodePort
  selector:
    app: golang
  ports:
    - name: main
      protocol: TCP
      port: {{.Values.goport}}
      targetPort: {{.Values.goport}}
      nodePort: 30001

